databases:
  - name: oooe_DB
    databaseName: oooe_db
    user: yasai
    region: singapore

services:
  - type: web
    name: yasai
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: oooe_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

